### ISSUE TITLE
Connecting the RaspberryPi & Arduino

### ISSUE THREAD

**Issue by baan20ty** [IMS-Group-7/Mower-Raspberry#2]
### Description of the task
For the robot to be able to receive remote driving commands, the RaspberryPi & Arduino need to communicate

---

### User story
As a developer, I want to connect the RaspberryPi and the Arduino

---

### Definitions of Done
- [x] The Raspberry Pi and Arduino are connected using UART communication protocol
   - [x] Have output to Arduino implemented
   - [x] Have input from Arduino implemented
   - [x] Test and verify

**Comment by TypoTami** [comment]
Just waiting for a chance to test IRL
