### ISSUE TITLE
Have the rover be able to map out the boundry

### ISSUE THREAD

**Issue by TypoTami** [IMS-Group-7/Mower-Raspberry#21]
### Description of the task
The mower should be able to use historical information combined with odometer data, to be able to dynamicly map out the boundry. Which in turn can be used in future pathfinding applications

---

### User story
As a developer, I want to be able to process boundry events from the rover and use it in conjunction with odometry data to map out a boundry.

---

### Definitions of Done
- [x] #17 
- [x] Recive boundry events from the rover, and mark down the points where this occurs
- [x] Perform a convex hull algorithm to get the outline of the known boundry
  - [x] Research which algorithm would be best for this: (Wikipedia has a few leads here)[https://en.wikipedia.org/wiki/Convex_hull_algorithms]
- ~~[ ] Convert the resulting polygon to a 2d grid for future paththing algorithms~~

**Comment by baan20ty** [comment]
@TypoTami; Rover is up-to-date with sending a "BORDER" flag every time it hits it.
